general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = killall -9 openrgb && pidof hyprlock || hyprlock --no-fade-in --immediate
    after_sleep_cmd = hyprctl dispatch dpms on && openrgb
}
listener {
    timeout = 600
    on-timeout = hyprlock --grace 10
}

listener {
    timeout = 3600                                                    # 5.5min
    on-timeout = hyprctl dispatch dpms off                            # screen off when timeout has passed
    on-resume = hyprctl dispatch dpms on && brightnessctl -r          # screen on when activity is detected after timeout has fired.
}

listener {
    timeout = 5400                                # 1.5h
    on-timeout = systemctl suspend                # suspend pc
}
