splash = false

# Desktop

wallpaper {
    monitor = DP-4
    path = /home/austin/Pictures/Wallpapers/Moonlight/Moonlight 16-9.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-5
    path = /home/austin/Pictures/Wallpapers/Moonlight/Moonlight 9-16 (Edited).png
    fit_mode = cover
}

# Laptop

wallpaper {
    monitor = eDP-1
    path = /home/austin/Pictures/Wallpapers/Moonlight/Moonlight 16-9.png
    fit_mode = cover
}