-- Generated by HyprMod
hl.config({
    cursor = {
        no_hardware_cursors = 0,
    },
    decoration = {
        blur = {
            popups = 1,
        },
        shadow = {
            range = 10,
        },
    },
    dwindle = {
        preserve_split = 1,
        smart_split = 0,
    },
    ecosystem = {
        no_donation_nag = 1,
    },
    general = {
        border_size = 3,
    },
    misc = {
        animate_manual_resizes = 1,
        animate_mouse_windowdragging = 1,
        key_press_enables_dpms = 1,
        mouse_move_enables_dpms = 1,
    },
})
