wallpaper {
    monitor = DP-4
    path = /home/austin/Downloads/wallhaven-727q29.jpg
    fit_mode = cover
}
wallpaper {
    monitor = DP-5
    path = /home/austin/Downloads/wallhaven-727q29.jpg
    fit_mode = cover
}