require("modules.aesthetics")
require("modules.autostart")
require("modules.desktop")
require("modules.environment")
require("modules.input-rules")
require("modules.keybindings")
require("modules.monitors")
require("modules.permissions")
require("modules.plugins")
require("modules.window-rules")
require("modules.laptop")
require("hyprland-gui")

