-- Generated by HyprMod

-- Settings
hl.config({
    cursor = {
        no_hardware_cursors = 0,
    },
    decoration = {
        blur = {
            popups = true,
        },
        shadow = {
            range = 10,
        },
    },
    dwindle = {
        preserve_split = true,
        smart_split = false,
    },
    ecosystem = {
        no_donation_nag = true,
    },
    general = {
        border_size = 3,
    },
    misc = {
        animate_manual_resizes = true,
        animate_mouse_windowdragging = true,
    },
})
