wallpaper {
    monitor = DP-4
    path = /home/austin/Pictures/Wallpapers/current_wallpaper.jpg
    fit_mode = cover
}
wallpaper {
    monitor = DP-5
    path = /home/austin/Pictures/Wallpapers/current_wallpaper.jpg
    fit_mode = cover
}
wallpaper {
    monitor = eDP-1
    path = /home/austin/Pictures/Wallpapers/current_wallpaper.jpg
    fit_mode = cover
}

splash = false