hl.on("hyprland.start", function()
    hl.exec_cmd("vicinae server")
    hl.exec_cmd("hyprpaper &")
    hl.exec_cmd("vesktop")
    hl.exec_cmd("Telegram")
    hl.exec_cmd("quickshell &")
    hl.exec_cmd("hyprtoolkit &")
    hl.exec_cmd("hyprpm reload")
    hl.exec_cmd("[workspace 1] brave")
    hl.exec_cmd("syncthing serve --no-browser")
    hl.exec_cmd("/usr/libexec/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("dbus-update-activation-environment --all")
    hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
end)