#############################
### ENVIRONMENT VARIABLES ###
#############################

# https://wiki.hypr.land/Configuring/Environment-variables/
env = XDG_SESSION_DESKTOP=Hyprland
env = XDG_CURRENT_DESKTOP=Hyprland
env = XDG_SESSION_TYPE,wayland
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = GDM_BACKEND,nvidia-drm
env = renderer,nvidia
env = NVD_BACKEND,direct
env = MOZ_ENABLE_WAYLAND =1
env = CLUTTER_BACKEND = wayland
env = XCURSOR_SIZE,24
env = AQ_NO_MODESET_COMMIT,1
env = WLR_DRM_NO_ATOMIC,1
env = WB_FORCE_SYSTEM_COLORS=1

env = HYPRCURSOR_THEME,Adwaita-Moonlight
env = HYPRCURSOR_SIZE,28

env = GTK_THEME=catppuccin-moonlight
env = GDK_BACKEND,wayland,x11,*

env = QT_QPA_PLATFORM, wayland;xcb
env = QT_WAYLAND_DISABLE_WINDOWDECORATION, 1 # Disable Qt window decorations under Wayland
env = QT_QPA_PLATFORMTHEME,qt5ct

env = NEWT_COLORS='root=#c8d3f5,#222436;border=#131421,#1e2030;window=#c8d3f5,#1e2030;shadow=#222436,#222436;title=#c8d3f5,#222436;button=#c8d3f5,#1e2030;actbutton=#c8d3f5,#444a73;checkbox=black,#c8d3f5;actcheckbox=#c8d3f5,#444a73;entry=#c8d3f5,#1e2030;label=#c8d3f5,#1e2030;listbox=#c8d3f5,#1e2030;actlistbox=#7cafff,#1e2030;textbox=#c8d3f5,#1e2030;acttextbox=#c8d3f5, #131421;helpline=#131421,#1e2030;roottext=#131421,#1e2030;emptyscale=red,#c8d3f5;fullscale=green,#c8d3f5;disabled_entry=gray,#c8d3f5;compactbutton=#c8d3f5,#131421;actsellistbox=#d5def8,#444a73;sellistbox=black,#444a73'   

xwayland {
  force_zero_scaling = true # set to true if app/text looks pixelated
}