###################
### MY PROGRAMS ###
###################

# https://wiki.hypr.land/Configuring/Keywords/

$terminal = kitty
$fileManager = nautilus
$menu = wofi 
$browser = flatpak run com.brave.Browser
#$logoutMenu = /home/austin/wleave/target/release/wleave --protocol xdg
$logoutMenu = wlogout
$wallpaper = "~/Downloads/wallhaven-727q29.jpg"
<<<<<<< HEAD
$codeEditor = code
=======
$codeEditor = code
>>>>>>> ada75c0e2b00980be8e1a428ebb82c30e63db474
