###################
### MY PROGRAMS ###
###################

# https://wiki.hypr.land/Configuring/Keywords/

$terminal = kitty
$fileManager = nautilus -w
$menu = vicinae toggle # wofi 
$browser = brave
#$logoutMenu = /home/austin/wleave/target/release/wleave --protocol xdg
$logoutMenu = wlogout
$wallpaper = "~/Downloads/wallhaven-727q29.jpg"
$codeEditor = code -n
$textEditor = gnome-text-editor -n
$smartSplitOn = hyprctl keyword dwindle:smart_split 1
$smartSplitOff = hyprctl keyword dwindle:smart_split 0
$preserveSplitOn = hyprctl keyword dwindle:preserve_split 1
$preserveSplitOff = hyprctl keyword dwindle:preserve_split 0