##############################
### WINDOWS AND WORKSPACES ###
##############################

# https://wiki.hypr.land/Configuring/Window-Rules/
# https://wiki.hypr.land/Configuring/Workspace-Rules/

windowrule = float on, match:class ^(mpc-qt)$, match:title ^(Media Player Classic Qute Theater)$
windowrule = float on, opacity 1.0 override, match:class ^(waypaper)$
windowrule = float on, match:class ^(org.pulseaudio.pavucontrol)$
windowrule = float on, match:class ^(xdg-desktop-portal-gtk)$
windowrule = float on, match:title ^(Choose Files)$
windowrule = float on, match:title ^(Bluetooth Devices)$
windowrule = float on, match:title ^(Open Folder)$
windowrule = float on, match:title ^("Sign in - Google Accounts - Brave")$
windowrule = float on, match:title ^(Friends List)$
windowrule = float on, stay_focused on, match:title ^(wleave)$
windowrule = float on, match:title ^(Media viewer)$
windowrule = float on, match:title ^(Welcome to Xbox)$
windowrule = size 800 600, match:class ^(org.pulseaudio.pavucontrol)$
windowrule = focus_on_activate true, match:class ^(brave-browser)$
windowrule = focus_on_activate true, match:class ^(nautilus)$
windowrule = opacity 1.0, match:title ^(Minecraft)$
# windowrule = workspace 9, match:class ^(kitty)$, match:title ^(hyprmod)$
windowrule = float on, match:class ^(io.github.bluemancz.hyprmod)$

# Ignore maximize requests from apps
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

layerrule = animation slide right, blur on, ignore_alpha 0.5, dim_around off, match:namespace swaync-control-center
layerrule = animation popin 90%, dim_around on, match:namespace logout_dialog
layerrule = animation popin 0%, match:namespace wofi
layerrule = animation off, match:namespace hyprpaper
layerrule = blur on, ignore_alpha 0, match:namespace vicinae


layerrule = animation slide up, match:namespace waybar
layerrule = animation slide up, match:namespace quickshell
layerrule = animation none, match:namespace hyprpicker
layerrule = animation fade, match:namespace selection

workspace = 1, monitor:DP-4
workspace = 2, monitor:DP-4
workspace = 3, monitor:DP-4
workspace = 4, monitor:DP-4
workspace = 5, monitor:DP-4
workspace = 6, monitor:DP-4
workspace = 7, monitor:DP-4
workspace = 8, monitor:DP-4
workspace = 9, monitor:DP-4
workspace = 10, monitor:DP-5
workspace = 11, monitor:DP-5
workspace = 12, monitor:DP-5
workspace = 13, monitor:DP-5
workspace = 14, monitor:DP-5
workspace = 15, monitor:DP-5
workspace = 16, monitor:DP-5
workspace = 17, monitor:DP-5
workspace = 18, monitor:DP-5
workspace = 19, monitor:DP-5

# windowrule = move ((monitor_w*0.5)-(window_w*0.5)) ((monitor_h*0.5) + (window_h*0.5)), match:class Mysql-workbench-bin negative:title  MySQL Workbench 

# windowrule = border_color rgba() rgba() 45deg, match:title ^(python jarvis.py)$